version: 2

jobs:
  lint_and_test:
    working_directory: ~/centralized-metadata-dags
    docker:
      - image: cimg/python:3.11.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: 'Install Dependencies'
          command: |
            SLUGIFY_USES_TEXT_UNIDECODE=yes pipenv install --dev

      - run:
          name: 'Check Airflow Constraints'
          command: |
            make compare-dependencies

      - run:
          name: 'Run Pylint'
          command: |
            make lint

      - run:
          name: 'Run Pytest'
          command: |
            make test

workflows:
  version: 2
  build_test:
    jobs:
      - lint_and_test
