version: 2

jobs:
  lint_and_test:
    working_directory: ~/centralized-metadata-dags
    docker:
      - image: cimg/python:3.9.10
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: 'Run Pylint & Pytest'
          command: |
            SLUGIFY_USES_TEXT_UNIDECODE=yes pipenv install --dev
            make lint
            make test

workflows:
  version: 2
  build_test:
    jobs:
      - lint_and_test
