#!/usr/bin/env bash

# pylint -E only throws errors for exceptions.

# The following files have been vetted with just "pylint" which is a lot more
# opinionated.

pipenv run pylint centralized_metadata
